accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout', views.user_logout, name='user_logout'),
]

home/urls.py
from django.urls import path
from .views import home, todo_detail, todo_delete, todo_create, update_todo

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('detail/<int:pk>/', todo_detail, name='detail'),
    path('delete/<int:pk>/', todo_delete, name='delete'),
    path('new_todo/', todo_create, name='new_todo'),
    path('update-todo/<int:pk>/', update_todo, name='update_todo'),
]

simple_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models


class ToDo(models.Model):
    title = models.CharField(max_length=30, verbose_name='موضوع')
    body = models.TextField(verbose_name='توضیحات')
    created = models.DateTimeField(verbose_name='زمان ساخت')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'todo'
        verbose_name = 'کار'
        verbose_name_plural = 'لیست کار ها'
        ordering = ('-created',)

accounts/forms.py
from django import forms


class UserRegisterForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput, max_length=30, label='نام')
    last_name = forms.CharField(widget=forms.TextInput, max_length=50, label='نام خانوادگی')
    username = forms.CharField(widget=forms.TextInput, max_length=30, label='نام کاربری')
    email = forms.EmailField(widget=forms.EmailInput, max_length=50, label='ایمیل')
    password = forms.CharField(widget=forms.PasswordInput, max_length=50, label='رمز عبور')


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput, max_length=30, label='نام کاربری')
    password = forms.CharField(widget=forms.PasswordInput, max_length=50, label='رمز عبور')

home/forms.py
from django import forms
from .models import ToDo


class NewTodoForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput, max_length=30)
    body = forms.CharField(widget=forms.Textarea)
    created = forms.DateTimeField()


class UpdateTodoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ('title', 'body', 'created')

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UserLoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


def user_register(request):
    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['username']
            email = cd['email']
            password = cd['password']
            user = User.objects.create_user(username, email, password)
            user.first_name = cd['first_name']
            user.last_name = cd['last_name']
            user.save()
            messages.success(request, 'یوزر با موفقیت ساخته شد.', extra_tags='success')
            return redirect('home:home')

    else:
        form = UserRegisterForm()
    return render(request, 'account/user_register.html', {'form': form})


def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['username']
            password = cd['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'با موفقیت وارد شدید.', extra_tags='success')
                return redirect('home:home')
            else:
                messages.error(request, 'اطلاعات وارد شده صحیح نمیباشد.', 'danger')
    else:
        form = UserLoginForm()
    return render(request, 'account/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'خارج شدید.', extra_tags='success')
    return redirect('home:home')

home/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from .forms import NewTodoForm, UpdateTodoForm
from .models import ToDo


def home(request):
    todo = ToDo.objects.all()
    return render(request, 'home/home.html', {'todo': todo})


def todo_detail(request, pk):
    detail = ToDo.objects.get(id=pk)
    return render(request, 'home/detail.html', {'detail': detail})


def todo_delete(request, pk):
    ToDo.objects.get(id=pk).delete()
    messages.success(request, 'تسک موردنظر شما با موفقیت حذف شد.', extra_tags='success')
    return redirect('home:home')


def todo_create(request):
    if request.method == "POST":
        form = NewTodoForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            title = cd['title']
            body = cd['body']
            created = cd['created']
            ToDo.objects.create(title=title, body=body, created=created)
            messages.success(request, 'تسک جدید با موفقیت ایجاد شد.', extra_tags='success')
            return redirect('home:home')
    else:
        form = NewTodoForm()
    return render(request, 'home/new_todo.html', {'form': form})


def update_todo(request, pk):
    todo = ToDo.objects.get(id=pk)
    if request.method == "POST":
        form = UpdateTodoForm(data=request.POST, instance=todo)
        if form.is_valid():
            form.save()
            messages.success(request, 'تسک مورد نظر شما با موفقیت تغییر یافت.', extra_tags='success')
            return redirect('home:detail', pk)
    else:
        form = UpdateTodoForm(instance=todo)
    return render(request, 'home/update_todo.html', {'form': form})

templates/home/detail.html
{% extends 'home/home.html' %}
{% load static %}

{% block title %} ->{{ detail.title }} {% endblock %}
{% block head %}{% endblock %}

{% block body %}
    <a href="{% url 'home:delete' detail.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'home:update_todo' detail.id %}" class="btn btn-info">Update</a>
    <h3>{{ detail.title }}</h3>
    <small>{{ detail.created }}</small>
    <hr>
    <p>{{ detail.body }}</p>

{% endblock %}

templates/home/home.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
    <title>
        TODO
        {% block title %}{% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body class="jumbotrun">
{% include "other/navigation.html" %}

{% include 'other/messages.html' %}

{% if request.user.is_authenticated %}
    <h3 class="user_name">{{ request.user }}</h3>
{% endif %}

<div class="card">
    {% for obj in todo %}
        <h3>{{ forloop.counter }} -
            <a class="card-body" href="{% url 'home:detail' obj.id %}">{{ obj.title }}</a></h3>
        <br>
    {% endfor %}
</div>
{% block body %}{% endblock %}

</body>
</html>

templates/home/new_todo.html
{% extends 'home/home.html' %}
{% load static %}
{% block title %}new-todo{% endblock %}
{% block head %}{% endblock %}

{% block body %}
    <h1>اضافه کردن تسک جدید</h1>
    <form method="POST">
        {% csrf_token %}
        موضوع:
        <input type="text" name="title">
        <br>
        توضیحات:
        <textarea name="body"></textarea>
        <br>
        زمان:
        <input type="datetime-local" name="created">
        <br><br>
        <input type="submit" value="ثبت">
    </form>
    {% if form.errors %}
        لطفا خطاهای زیر را رفع کنید:
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                    <br>
                {% endfor %}
            {% endif %}
        {% endfor %}
        {% if form.non_field_errors %}
            {{ form.non_field_errors }}
        {% endif %}
    {% endif %}
{% endblock %}

templates/home/update_todo.html
{% extends 'home/home.html' %}
{% load static %}
{% block title %} update-todo {% endblock %}
{% block head %}{% endblock %}

{% block body %}
    <h1>تغییر اطلاعات تسک</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ثبت تغییرات">
{% endblock %}

templates/other/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
{% endif %}

templates/other/navigation.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" disabled="">TODO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:new_todo' %}">New-Todo</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user_logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user_register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user_login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>